app:
  currentEnv: dev
  devEmails:
    - labyu2020@gmail.com

server:
  port: 8080
  tomcat:
    max-http-form-post-size: 10MB
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true
      force-request: true
      enabled: true

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/apjung?serverTimezone=Asia/Seoul&charset=UTF-8
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        formar_sql: true
        dialect: me.apjung.backend.component.custommysqldialect.CustomMySqlDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
    mode: HTML

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          ssl:
            enable: true
        transport:
          protocol: smtp
        mime:
          charset: UTF-8

  flyway:
    enabled: false
    url: jdbc:mysql://${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/apjung?serverTimezone=Asia/Seoul&charset=UTF-8
    user: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
    baseline-version: 0
    out-of-order: true

jwt:
  access-token-props:
    secret: ${ACCESS_TOKEN_SECRET}
    expiration-time-milli-sec: ${ACCESS_TOKEN_EXPIRATION_TIME_MILLI_SEC}
  refresh-token-props:
    secret: ${REFRESH_TOKEN_SECRET}
    expiration-time-milli-sec: ${REFRESH_TOKEN_EXPIRATION_TIME_MILLI_SEC}

security:
  permittedEndpoints:
    - "/"
    - "/health"
    - "/h2-console"
    - "/h2-console/**"
    - "/auth/register"
    - "/auth/login"
    - "/auth/token"
    - "/docs/**"
    - "/**/callback/**"

storage:
  s3Bucket: storage.apjung.xyz
  s3Public: https://storage.apjung.xyz