app:
  currentEnv: dev

server:
  port: 8080
  tomcat:
    max-http-form-post-size: 10MB
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true
      force-request: true
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/apjung?serverTimezone=Asia/Seoul&charset=UTF-8
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQ_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        formar_sql: true
        dialect: me.apjung.backend.component.CustomMySqlDialect.CustomMySqlDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

