POST {{apiUrl}}/auth/register
Content-Type: application/json

{
  "email" : "{{USER_EMAIL}}",
  "password" : "{{USER_PASSWORD}}",
  "name" : "{{USER_NAME}}",
  "mobile" : "{{USER_MOBILE}}"
}

###

POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email" : "{{USER_EMAIL}}",
  "password" : "{{USER_PASSWORD}}"
}

> {%
client.global.set("authorizationToken", response.body.tokenType + " " + response.body.token);
client.log("Auth Token : " + client.global.get("authorizationToken"));
%}

###

GET {{apiUrl}}/auth/me
Authorization: {{authorizationToken}}
