POST {{apiUrl}}/auth/register
Content-Type: application/json

{
  "email" : "{{USER_EMAIL}}",
  "password" : "{{USER_PASSWORD}}",
  "name" : "{{USER_NAME}}",
  "mobile" : "{{USER_MOBILE}}"
}

###

POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email" : "{{USER_EMAIL}}",
  "password" : "{{USER_PASSWORD}}"
}

> {%
client.global.set("authorizationToken", response.body.accessToken.type + " " + response.body.accessToken.token);
client.global.set("refreshToken", response.body.refreshToken.type + " " + response.body.refreshToken.token);
client.log("Auth Token : " + client.global.get("authorizationToken"));
client.log("RefreshToken : " + client.global.get("refreshToken"));
%}

###

POST {{apiUrl}}/auth/token
Content-Type: application/json

{
    "grantType": "{{GRANT_TYPE}}",
    "refreshToken": "{{refreshToken}}"
}

> {%
client.global.set("authorizationToken", response.body.accessToken.type + " " + response.body.accessToken.token);
client.log("Auth Token : " + client.global.get("authorizationToken"));
%}

###

GET {{apiUrl}}/auth/me
Authorization: {{authorizationToken}}
